pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                script {
                    openshift.withCluster(){
                        openshift.withProject() {
                            def buildSelector = bc.startBuild(gitbook-centos-docker)
                            buildSelector.logs('-f')
                    }
                }
            }
        }
     }
   }
}
